FROM php:8.2-apache

ENV Version=4.6.1
WORKDIR /src

RUN sed -i 's@deb.debian.org@mirror.kakao.com@g' /etc/apt/sources.list.d/debian.sources
RUN sed -i 's@mirror.kakao.com/debian-security@deb.debian.org/debian-security@g' /etc/apt/sources.list.d/debian.sources

RUN	apt-get update \
	&& apt-get -qqy install wget libldb-dev libldap2-dev ssh iputils-ping bind9-utils \
	&& wget http://facilemanager.com/download/facilemanager-complete-$Version.tar.gz \
	&& tar -xvf facilemanager-complete-$Version.tar.gz \
	&& mv facileManager/server/* /var/www/html/ \
	&& mkdir /fm_tmp/ \
	&& chown -R www-data:www-data /fm_tmp/ \
    && chown -R www-data:www-data /var/www/html/ \
    && ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so \
	&& docker-php-ext-install mysqli ldap \
	&& a2enmod rewrite dump_io 

COPY config.inc.php /var/www/html/
COPY php.ini /usr/local/etc/php/php.ini
COPY init.php.patch /var/www/html/fm-includes/

RUN patch /var/www/html/fm-includes/init.php /var/www/html/fm-includes/init.php.patch

RUN	rm -rf /var/lib/apt/lists/* \
	&& rm -rf /src/facileManager
